const TYPES = {
  ADD_CATEGORIES_REQUEST: 'ADD_CATEGORIES_REQUEST',
  ADD_CATEGORIES_SUCCESS: 'ADD_CATEGORIES_SUCCESS',
  ADD_CATEGORIES_ERROR: 'ADD_CATEGORIES_ERROR',

  GET_CATEGORIES_LIST_REQUEST: 'GET_CATEGORIES_LIST_REQUEST',
  GET_CATEGORIES_LIST_SUCCESS: 'GET_CATEGORIES_LIST_SUCCESS',
  GET_CATEGORIES_LIST_ERROR: 'GET_CATEGORIES_LIST_ERROR',

  DELETE_CATEGORIES_REQUEST: 'DELETE_CATEGORIES_REQUEST',
  DELETE_CATEGORIES_SUCCESS: 'DELETE_CATEGORIES_SUCCESS',
  DELETE_CATEGORIES_ERROR: 'DELETE_CATEGORIES_ERROR',
};

export default TYPES;
