const TYPES = {
  ADD_TODO_REQUEST: 'ADD_TODO_REQUEST',
  ADD_TODO_SUCCESS: 'ADD_TODO_SUCCESS',
  ADD_TODO_ERROR: 'ADD_TODO_ERROR',

  GET_TODO_LIST_REQUEST: 'GET_TODO_LIST_REQUEST',
  GET_TODO_LIST_SUCCESS: 'GET_TODO_LIST_SUCCESS',
  GET_TODO_LIST_ERROR: 'GET_TODO_LIST_ERROR',

  TOGGLE_TODO_REQUEST: 'TOGGLE_TODO_REQUEST',
  TOGGLE_TODO_SUCCESS: 'TOGGLE_TODO_SUCCESS',
  TOGGLE_TODO_ERROR: 'TOGGLE_TODO_ERROR',

  DELETE_TODO_REQUEST: 'DELETE_TODO_REQUEST',
  DELETE_TODO_SUCCESS: 'DELETE_TODO_SUCCESS',
  DELETE_TODO_ERROR: 'DELETE_TODO_ERROR',
};

export default TYPES;
